/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Returned to the admin when they generate an activation code.
 */
export interface ActivationCodeResponse {
  code: string;
  device_id: string;
  expires_at: string;
}
