/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface AddOrderItem {
  menu_item_id: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  quantity?: number | null;
}
