/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface AddServiceCharge {
  amount_minor_unit: number;
  /** @nullable */
  created_by?: string | null;
  name: string;
  /** @nullable */
  rate_bps?: number | null;
}
