/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface Allergen {
  code: string;
  display_order: number;
  id: string;
  is_active: boolean;
  name: string;
}
