/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { ApiTokenResponse } from './apiTokenResponse';

/**
 * Response returned only at creation time — includes the full token.
 */
export type ApiTokenCreatedResponse = ApiTokenResponse & {
  /** The full API token. Shown only once — store it securely. */
  secret: string;
};
