/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { DiscountType } from './discountType';

export interface ApplyLineDiscount {
  /** @nullable */
  applied_by?: string | null;
  /** @nullable */
  code?: string | null;
  discount_type: DiscountType;
  /** @nullable */
  reason?: string | null;
  value: number;
}
