/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface BundleSlotOption {
  bundle_slot_id: string;
  display_order: number;
  id: string;
  is_default: boolean;
  menu_item_id: string;
  price_adjustment_minor_unit: number;
  tenant_id: string;
}
