/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface BundleSlot {
  bundle_item_id: string;
  created_at: string;
  display_order: number;
  id: string;
  max_selections: number;
  min_selections: number;
  name: string;
  tenant_id: string;
  updated_at: string;
}
