/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface BundleSlotOptionInput {
  /** @nullable */
  display_order?: number | null;
  /** @nullable */
  is_default?: boolean | null;
  menu_item_id: string;
  /** @nullable */
  price_adjustment_minor_unit?: number | null;
}
