/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */

export interface BundleSlotOptionInput {
  /** @nullable */
  display_order?: number | null;
  /** @nullable */
  is_default?: boolean | null;
  menu_item_id: string;
  /** @nullable */
  price_adjustment_minor_unit?: number | null;
}
