/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */

export interface CapturePayment {
  /** @nullable */
  card_details?: string | null;
  /** @nullable */
  external_ref?: string | null;
  /**
   * Operator capturing the payment (required when register_id is set).
   * @nullable
   */
  operator_id?: string | null;
  /**
   * Register ID for fiscal receipt generation.
   * @nullable
   */
  register_id?: string | null;
}
