/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface Category {
  /** @nullable */
  color?: string | null;
  created_at: string;
  display_order: number;
  /** @nullable */
  icon?: string | null;
  id: string;
  is_active: boolean;
  name: string;
  /** @nullable */
  parent_id?: string | null;
  tenant_id: string;
  updated_at: string;
}
