/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface CompleteRefund {
  /**
   * Operator completing the refund (required when register_id is set).
   * @nullable
   */
  operator_id?: string | null;
  /**
   * Register ID for fiscal receipt generation.
   * @nullable
   */
  register_id?: string | null;
}
