/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { StockMovementType } from './stockMovementType';

export interface CreateStockMovement {
  /** @nullable */
  created_by?: string | null;
  movement_type: StockMovementType;
  /** @nullable */
  order_item_id?: string | null;
  quantity_delta: number;
  /** @nullable */
  reference?: string | null;
  stock_item_id: string;
}
