/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateLocation {
  address: string;
  city: string;
  country?: string;
  name: string;
  /** @nullable */
  org_number?: string | null;
  postal_code: string;
  settlement_time?: string;
  timezone?: string;
}
