/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { StockMovementType } from './stockMovementType';

export interface CreateStockMovement {
  /** @nullable */
  created_by?: string | null;
  movement_type: StockMovementType;
  /** @nullable */
  order_item_id?: string | null;
  quantity_delta: number;
  /** @nullable */
  reference?: string | null;
  stock_item_id: string;
}
