/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateCategory {
  /** @nullable */
  color?: string | null;
  /** @nullable */
  display_order?: number | null;
  /** @nullable */
  icon?: string | null;
  name: string;
  /** @nullable */
  parent_id?: string | null;
}
