/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { OrderType } from './orderType';

export interface CreateOrder {
  /** @nullable */
  created_by?: string | null;
  /** @nullable */
  notes?: string | null;
  order_type?: null | OrderType;
  /** @nullable */
  tab_id?: string | null;
}
