/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateRegister {
  /** @nullable */
  location_id?: string | null;
  name: string;
  register_id: string;
}
