/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { RefundMode } from './refundMode';

export interface CreateRefund {
  /** @nullable */
  created_by?: string | null;
  idempotency_key: string;
  mode: RefundMode;
  payment_id: string;
  reason: string;
  /**
   * Register ID for fiscal receipt generation (cash auto-complete only).
   * @nullable
   */
  register_id?: string | null;
}
