/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateMenuItem {
  /** @nullable */
  category_id?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  display_order?: number | null;
  name: string;
  price_minor_unit: number;
  /** @nullable */
  sku?: string | null;
  /** @nullable */
  tax_rate_id?: string | null;
}
