/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateModifierGroup {
  /** @nullable */
  display_order?: number | null;
  /** @nullable */
  max_selections?: number | null;
  /** @nullable */
  min_selections?: number | null;
  name: string;
}
