/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { OrderType } from './orderType';

export interface CreateOrder {
  /** @nullable */
  created_by?: string | null;
  /** @nullable */
  notes?: string | null;
  order_type?: null | OrderType;
  /** @nullable */
  tab_id?: string | null;
}
