/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { PaymentMethod } from './paymentMethod';
import type { PaymentMode } from './paymentMode';

export interface CreatePayment {
  /** @nullable */
  created_by?: string | null;
  /** @nullable */
  currency?: string | null;
  idempotency_key: string;
  method: PaymentMethod;
  mode: PaymentMode;
  /**
   * Register ID for fiscal receipt generation. If set, a receipt is
generated atomically within the payment transaction (cash only).
   * @nullable
   */
  register_id?: string | null;
  /** @nullable */
  tab_id?: string | null;
  /** @nullable */
  terminal_id?: string | null;
  /** @nullable */
  tip_minor_unit?: number | null;
}
