/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateStockItem {
  /** @nullable */
  initial_quantity?: number | null;
  /** @nullable */
  is_tracked?: boolean | null;
  location_id: string;
  menu_item_id: string;
  /** @nullable */
  reorder_point?: number | null;
}
