/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type CredentialType = typeof CredentialType[keyof typeof CredentialType];


export const CredentialType = {
  pin: 'pin',
  rfid: 'rfid',
  password: 'password',
} as const;
