/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { CredentialType } from './credentialType';

export interface CredentialSummary {
  created_at: string;
  credential_type: CredentialType;
  id: string;
  is_active: boolean;
}
