/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface Device {
  /** @nullable */
  activated_at?: string | null;
  created_at: string;
  fingerprint?: unknown;
  id: string;
  is_active: boolean;
  /** @nullable */
  last_seen_at?: string | null;
  name: string;
  /** @nullable */
  register_id?: string | null;
  tenant_id: string;
}
