/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { Device } from './device';

/**
 * Returned to the device on successful activation. The token is
only returned once — the backend stores a hash.
 */
export interface DeviceTokenResponse {
  device: Device;
  token: string;
}
