/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */

export interface DeviceResponse {
  /** @nullable */
  activated_at?: string | null;
  created_at: string;
  fingerprint?: unknown;
  id: string;
  is_active: boolean;
  /** @nullable */
  last_seen_at?: string | null;
  name: string;
  /** @nullable */
  register_id?: string | null;
  tenant_id: string;
}
