/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { DeviceResponse } from './deviceResponse';

/**
 * Returned to the device on successful activation. The token is
only returned once — the backend stores a hash.
 */
export interface DeviceTokenResponse {
  device: DeviceResponse;
  token: string;
}
