/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface DiscardOrder {
  discard_reason: string;
  /** @nullable */
  discarded_by?: string | null;
  /**
   * Register ID for SAF-T event logging.
   * @nullable
   */
  register_id?: string | null;
}
