/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { DiscountScope } from './discountScope';
import type { DiscountType } from './discountType';

export interface Discount {
  applied_at: string;
  /** @nullable */
  applied_by?: string | null;
  /** @nullable */
  code?: string | null;
  discount_type: DiscountType;
  id: string;
  /** @nullable */
  order_id?: string | null;
  /** @nullable */
  order_item_id?: string | null;
  /** @nullable */
  reason?: string | null;
  resolved_amount_minor_unit: number;
  scope: DiscountScope;
  /** @nullable */
  tab_id?: string | null;
  tenant_id: string;
  value: number;
}
