/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type DiscountScope = typeof DiscountScope[keyof typeof DiscountScope];


export const DiscountScope = {
  Line: 'Line',
  Order: 'Order',
  Tab: 'Tab',
} as const;
