/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type ListStockItemsParams = {
/**
 * Location ID (required)
 */
location_id: string;
/**
 * Filter by tracking status
 */
is_tracked?: boolean;
/**
 * Only items at or below reorder point
 */
low_stock?: boolean;
};
