/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { StockMovementType } from './stockMovementType';

export type ListMovementsParams = {
/**
 * Filter by stock item
 */
stock_item_id?: string;
/**
 * Filter by type
 */
movement_type?: StockMovementType;
/**
 * Start date (ISO 8601)
 */
from?: string;
/**
 * End date (ISO 8601)
 */
to?: string;
};
