/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface Location {
  address: string;
  city: string;
  country: string;
  created_at: string;
  id: string;
  is_active: boolean;
  name: string;
  /** @nullable */
  org_number?: string | null;
  postal_code: string;
  /** When the business day ends and Z-report settlement runs.
A nightclub might set 06:00, meaning their day runs 06:00→06:00. */
  settlement_time: string;
  tenant_id: string;
  timezone: string;
}
