/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface LocationMenuOverride {
  created_at: string;
  id: string;
  is_available: boolean;
  location_id: string;
  menu_item_id: string;
  /** @nullable */
  price_minor_unit?: number | null;
  tenant_id: string;
  updated_at: string;
}
