/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface MenuItemAssignment {
  display_order: number;
  id: string;
  menu_item_id: string;
  /** @nullable */
  price_override_minor_unit?: number | null;
}
