/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response DTO for menu item images. Includes presigned URLs for direct browser access.
 */
export interface MenuItemImageResponse {
  /** @nullable */
  blurhash?: string | null;
  content_type: string;
  created_at: string;
  display_order: number;
  /** @nullable */
  height?: number | null;
  id: string;
  menu_item_id: string;
  size_bytes: number;
  /** @nullable */
  thumbnail_url?: string | null;
  url: string;
  /** @nullable */
  width?: number | null;
}
