/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface MenuItem {
  /** @nullable */
  category_id?: string | null;
  created_at: string;
  deposit_minor_unit: number;
  /** @nullable */
  description?: string | null;
  display_order: number;
  id: string;
  is_enabled: boolean;
  name: string;
  price_minor_unit: number;
  /** @nullable */
  sku?: string | null;
  /** @nullable */
  tax_rate_id?: string | null;
  tenant_id: string;
  updated_at: string;
}
