/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface Menu {
  /** @nullable */
  active_days?: number | null;
  /** @nullable */
  active_from?: string | null;
  /** @nullable */
  active_until?: string | null;
  created_at: string;
  display_order: number;
  id: string;
  is_active: boolean;
  name: string;
  tenant_id: string;
  updated_at: string;
}
