/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { UserSummary } from './userSummary';
import type { UserTenant } from './userTenant';

export interface MeResponse {
  tenants: UserTenant[];
  user: UserSummary;
}
