/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */

export interface ModifierResponse {
  created_at: string;
  display_order: number;
  id: string;
  is_active: boolean;
  modifier_group_id: string;
  name: string;
  price_minor_unit: number;
  tenant_id: string;
  updated_at: string;
}
