/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface ModifierGroupAssignment {
  display_order: number;
  id: string;
  modifier_group_id: string;
}
