/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */

export interface OrderItemTaxResponse {
  id: string;
  order_item_id: string;
  rate_bps: number;
  tax_amount_minor_unit: number;
  tax_name: string;
  tax_rate_id: string;
  taxable_amount_minor_unit: number;
  tenant_id: string;
}
