/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { OrderItemStatus } from './orderItemStatus';

export interface OrderItem {
  created_at: string;
  deposit_unit_minor_unit: number;
  /** @nullable */
  discard_reason?: string | null;
  /** @nullable */
  discarded_at?: string | null;
  /** @nullable */
  discarded_by?: string | null;
  id: string;
  item_name: string;
  menu_item_id: string;
  /** @nullable */
  notes?: string | null;
  order_id: string;
  quantity: number;
  status: OrderItemStatus;
  tenant_id: string;
  unit_price_minor_unit: number;
}
