/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];


export const OrderStatus = {
  Open: 'Open',
  Submitted: 'Submitted',
  Preparing: 'Preparing',
  Ready: 'Ready',
  Delivered: 'Delivered',
  Discarded: 'Discarded',
} as const;
