/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type OrderItemStatus = typeof OrderItemStatus[keyof typeof OrderItemStatus];


export const OrderItemStatus = {
  Active: 'Active',
  Discarded: 'Discarded',
} as const;
