/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type OrderType = typeof OrderType[keyof typeof OrderType];


export const OrderType = {
  EatIn: 'EatIn',
  TakeAway: 'TakeAway',
} as const;
