/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { OrderStatus } from './orderStatus';
import type { OrderType } from './orderType';

export interface Order {
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  /** @nullable */
  discard_reason?: string | null;
  /** @nullable */
  discarded_at?: string | null;
  /** @nullable */
  discarded_by?: string | null;
  id: string;
  /** @nullable */
  notes?: string | null;
  order_type: OrderType;
  sequence_num: number;
  status: OrderStatus;
  /** @nullable */
  submitted_at?: string | null;
  /** @nullable */
  tab_id?: string | null;
  tenant_id: string;
}
