/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface PaymentAllocation {
  amount_minor_unit: number;
  id: string;
  order_item_id: string;
  payment_id: string;
  tenant_id: string;
}
