/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */

export interface PaymentAllocationResponse {
  amount_minor_unit: number;
  id: string;
  order_item_id: string;
  payment_id: string;
  tenant_id: string;
}
