/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { PaymentMethod } from './paymentMethod';
import type { PaymentStatus } from './paymentStatus';

export interface Payment {
  amount_minor_unit: number;
  /** @nullable */
  captured_at?: string | null;
  /** @nullable */
  card_details?: string | null;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  currency: string;
  /** @nullable */
  external_ref?: string | null;
  /** @nullable */
  failed_at?: string | null;
  /** @nullable */
  failure_reason?: string | null;
  id: string;
  idempotency_key: string;
  method: PaymentMethod;
  status: PaymentStatus;
  /** @nullable */
  tab_id?: string | null;
  tenant_id: string;
  /** @nullable */
  terminal_id?: string | null;
  tip_minor_unit: number;
}
