/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type PaymentMode = {
  mode: 'items';
  order_item_ids: string[];
} | {
  amount_minor_unit: number;
  mode: 'amount';
} | {
  mode: 'full';
};
