/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type PaymentMethod = typeof PaymentMethod[keyof typeof PaymentMethod];


export const PaymentMethod = {
  Cash: 'Cash',
  Card: 'Card',
  Vipps: 'Vipps',
  GiftCard: 'GiftCard',
  Other: 'Other',
} as const;
