/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { PaymentAllocationResponse } from './paymentAllocationResponse';
import type { PaymentResponse } from './paymentResponse';

export interface PaymentWithAllocations {
  allocations: PaymentAllocationResponse[];
  /** False when an existing payment was returned due to idempotency key match. */
  created: boolean;
  payment: PaymentResponse;
  /**
   * Redirect URL for async payment flows (e.g., Vipps).
Present only when the payment requires customer approval via an external app.
   * @nullable
   */
  redirect_url?: string | null;
}
