/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type PaymentStatus = typeof PaymentStatus[keyof typeof PaymentStatus];


export const PaymentStatus = {
  Pending: 'Pending',
  Authorized: 'Authorized',
  Captured: 'Captured',
  Failed: 'Failed',
  Cancelled: 'Cancelled',
} as const;
