/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { Payment } from './payment';
import type { PaymentAllocation } from './paymentAllocation';

export interface PaymentWithAllocations {
  allocations: PaymentAllocation[];
  /** False when an existing payment was returned due to idempotency key match. */
  created: boolean;
  payment: Payment;
  /**
   * Redirect URL for async payment flows (e.g., Vipps).
Present only when the payment requires customer approval via an external app.
   * @nullable
   */
  redirect_url?: string | null;
}
