/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { RefundStatus } from './refundStatus';

export interface RefundResponse {
  amount_minor_unit: number;
  /** @nullable */
  completed_at?: string | null;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  /** @nullable */
  external_ref?: string | null;
  id: string;
  idempotency_key: string;
  payment_id: string;
  reason: string;
  status: RefundStatus;
  tenant_id: string;
}
