/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { Refund } from './refund';
import type { RefundAllocation } from './refundAllocation';

export interface RefundWithAllocations {
  allocations: RefundAllocation[];
  /** False when an existing refund was returned due to idempotency key match. */
  created: boolean;
  refund: Refund;
}
