/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface Register {
  created_at: string;
  id: string;
  is_active: boolean;
  /** @nullable */
  location_id?: string | null;
  name: string;
  register_id: string;
  tenant_id: string;
}
