/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface ServiceCharge {
  amount_minor_unit: number;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  id: string;
  name: string;
  /** @nullable */
  order_id?: string | null;
  /** @nullable */
  rate_bps?: number | null;
  /** @nullable */
  tab_id?: string | null;
  tenant_id: string;
}
