/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface SetLocationOverride {
  /** @nullable */
  is_available?: boolean | null;
  menu_item_id: string;
  /** @nullable */
  price_minor_unit?: number | null;
}
