/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { StaffRole } from './staffRole';

export interface Staff {
  created_at: string;
  id: string;
  is_active: boolean;
  name: string;
  role: StaffRole;
  tenant_id: string;
}
