/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type StaffRole = typeof StaffRole[keyof typeof StaffRole];


export const StaffRole = {
  Cashier: 'Cashier',
  ShiftLead: 'ShiftLead',
  Manager: 'Manager',
  Admin: 'Admin',
} as const;
