/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { StaffRole } from './staffRole';

export interface StaffResponse {
  created_at: string;
  id: string;
  is_active: boolean;
  name: string;
  role: StaffRole;
  tenant_id: string;
}
