/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface StockItemFilter {
  /** @nullable */
  is_tracked?: boolean | null;
  location_id: string;
  /** @nullable */
  low_stock?: boolean | null;
}
