/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type StockCountStatus = typeof StockCountStatus[keyof typeof StockCountStatus];


export const StockCountStatus = {
  Draft: 'Draft',
  InProgress: 'InProgress',
  Completed: 'Completed',
  Cancelled: 'Cancelled',
} as const;
