/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface StockCountLine {
  counted_quantity: number;
  expected_quantity: number;
  id: string;
  stock_count_id: string;
  stock_item_id: string;
  tenant_id: string;
}
