/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type StockMovementType = typeof StockMovementType[keyof typeof StockMovementType];


export const StockMovementType = {
  Received: 'Received',
  Sold: 'Sold',
  Returned: 'Returned',
  Wasted: 'Wasted',
  Adjustment: 'Adjustment',
  TransferOut: 'TransferOut',
  TransferIn: 'TransferIn',
} as const;
