/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { StockMovementType } from './stockMovementType';

export interface StockMovementFilter {
  /** @nullable */
  from?: string | null;
  movement_type?: null | StockMovementType;
  /** @nullable */
  stock_item_id?: string | null;
  /** @nullable */
  to?: string | null;
}
