/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { StockCountStatus } from './stockCountStatus';

export interface StockCount {
  /** @nullable */
  completed_at?: string | null;
  /** @nullable */
  completed_by?: string | null;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  id: string;
  location_id: string;
  /** @nullable */
  notes?: string | null;
  status: StockCountStatus;
  tenant_id: string;
}
