/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */

export interface StockCountLineResponse {
  counted_quantity: number;
  expected_quantity: number;
  id: string;
  stock_count_id: string;
  stock_item_id: string;
  tenant_id: string;
}
