/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface StockItem {
  created_at: string;
  current_quantity: number;
  id: string;
  is_tracked: boolean;
  location_id: string;
  menu_item_id: string;
  reorder_point: number;
  tenant_id: string;
  updated_at: string;
}
