/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { StockCountStatus } from './stockCountStatus';

export interface StockCountResponse {
  /** @nullable */
  completed_at?: string | null;
  /** @nullable */
  completed_by?: string | null;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  id: string;
  location_id: string;
  /** @nullable */
  notes?: string | null;
  status: StockCountStatus;
  tenant_id: string;
}
