/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { OrderType } from './orderType';
import type { TabStatus } from './tabStatus';

export interface Tab {
  /** @nullable */
  closed_at?: string | null;
  /** @nullable */
  closed_by?: string | null;
  currency: string;
  /** @nullable */
  display_name?: string | null;
  id: string;
  /** @nullable */
  notes?: string | null;
  opened_at: string;
  /** @nullable */
  opened_by?: string | null;
  order_type: OrderType;
  status: TabStatus;
  tenant_id: string;
}
