/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { OrderType } from './orderType';
import type { TabStatus } from './tabStatus';

export interface TabResponse {
  /** @nullable */
  closed_at?: string | null;
  /** @nullable */
  closed_by?: string | null;
  currency: string;
  /** @nullable */
  display_name?: string | null;
  id: string;
  /** @nullable */
  notes?: string | null;
  opened_at: string;
  /** @nullable */
  opened_by?: string | null;
  order_type: OrderType;
  status: TabStatus;
  tenant_id: string;
}
