/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export type TabStatus = typeof TabStatus[keyof typeof TabStatus];


export const TabStatus = {
  Open: 'Open',
  Closed: 'Closed',
  Discarded: 'Discarded',
} as const;
