/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Derived tab totals — never stored, always computed.
 */
export interface TabTotals {
  amount_paid: number;
  amount_refunded: number;
  amount_remaining: number;
  tab_total: number;
}
