/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface TaxRate {
  eat_in_rate_bps: number;
  id: string;
  is_default: boolean;
  name: string;
  take_away_rate_bps: number;
  tenant_id: string;
}
