/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface Tenant {
  created_at: string;
  id: string;
  is_active: boolean;
  is_test: boolean;
  name: string;
  slug: string;
}
