/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Terminal callback payload for asynchronous terminal responses.

Some terminal APIs send results via webhook instead of synchronous response.
This handler provides a fallback for that pattern.
 */
export interface TerminalCallback {
  /** @nullable */
  card_brand?: string | null;
  /** @nullable */
  card_masked_pan?: string | null;
  /** @nullable */
  error_message?: string | null;
  status: string;
  transaction_id: string;
  /** @nullable */
  transaction_ref?: string | null;
}
