/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateLocation {
  /** @nullable */
  address?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  is_active?: boolean | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  org_number?: string | null;
  /** @nullable */
  postal_code?: string | null;
  /** @nullable */
  settlement_time?: string | null;
  /** @nullable */
  timezone?: string | null;
}
