/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateMenuItem {
  /** @nullable */
  category_id?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  display_order?: number | null;
  /** @nullable */
  is_enabled?: boolean | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  price_minor_unit?: number | null;
  /** @nullable */
  sku?: string | null;
  /** @nullable */
  tax_rate_id?: string | null;
}
