/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateTaxRate {
  /** @nullable */
  eat_in_rate_bps?: number | null;
  /** @nullable */
  is_default?: boolean | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  take_away_rate_bps?: number | null;
}
