/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateMenu {
  /** @nullable */
  active_days?: number | null;
  /** @nullable */
  active_from?: string | null;
  /** @nullable */
  active_until?: string | null;
  /** @nullable */
  display_order?: number | null;
  /** @nullable */
  is_active?: boolean | null;
  /** @nullable */
  name?: string | null;
}
