/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { StaffRole } from './staffRole';

export interface UpdateStaff {
  /** @nullable */
  is_active?: boolean | null;
  /** @nullable */
  name?: string | null;
  role?: null | StaffRole;
}
