/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateTaxRate {
  /** @nullable */
  eat_in_rate_bps?: number | null;
  /** @nullable */
  is_default?: boolean | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  take_away_rate_bps?: number | null;
}
