/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */
import type { StockCountStatus } from './stockCountStatus';

export interface UpdateStockCount {
  /** @nullable */
  notes?: string | null;
  status?: null | StockCountStatus;
}
