/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateCategory {
  /** @nullable */
  color?: string | null;
  /** @nullable */
  display_order?: number | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  is_active?: boolean | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  parent_id?: string | null;
}
