/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface UpsertStockCountLine {
  counted_quantity: number;
  stock_item_id: string;
}
