/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */
import type { UserPasskeySummary } from './userPasskeySummary';
import type { UserProfile } from './userProfile';
import type { UserTenantExport } from './userTenantExport';

export interface UserExport {
  passkeys: UserPasskeySummary[];
  tenants: UserTenantExport[];
  user: UserProfile;
}
