/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface UserSummary {
  email: string;
  email_verified: boolean;
  id: string;
  name: string;
}
