/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * OpenAPI spec version: 0.1.0
 */

export interface UserPasskeySummary {
  created_at: string;
  id: string;
  name: string;
}
