/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SMLS API
 * Backend API for SMLS — a multi-tenant point-of-sale system. Admin endpoints manage tenants, menus, staff, devices, and inventory. POS endpoints power tablet-based ordering, payments, and receipts.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Vipps webhook callback payload.

Vipps sends callbacks to the URL configured when creating the payment.
The `reference` field contains our payment_id (set during initiation).
The `name` field identifies the event type.
 */
export interface VippsCallback {
  /** Event name, e.g. "epayments.payment.captured.v1". */
  name: string;
  /** Vipps transaction ID. */
  pspReference: string;
  /** Our payment_id, set as `reference` when creating the Vipps payment. */
  reference: string;
}
